language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - pip install --upgrade pytest  # https://github.com/travis-ci/travis-ci/issues/4873
  - pip install --upgrade pip wheel virtualenv setuptools
  - pip install coveralls
install:
  - pip install -e .
script: coverage run --source=kaptan setup.py test 
after_success:
  - bash <(curl -s https://codecov.io/bash)
